steps:
- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install -U pip setuptools'
  displayName: python -m pip install -U pip setuptools

- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install pyparsing pyyaml'
  displayName: python -m pip install pyparsing pyyaml

- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install EmPy'
  displayName: python -m pip install EmPy

- task: CmdLine@1
  inputs:
    filename: python
    arguments: '-m pip install vcstool'
  displayName: python -m pip install vcstool

- task: BatchScript@1
  inputs:
    filename: 'ci-scripts/build-uwp.bat'
    modifyEnvironment: false
  displayName: Build ROS2 .Net

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\dev\ament'
    Contents: 'install\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy Ament artifacts

- task: CopyFiles@2
  inputs:
    SourceFolder: 'D:\dev\ros2'
    Contents: 'install\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy ROS2 .Net artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ros2-dotnet'
    publishLocation: Container
  displayName: Publish ROS2 .Net artifacts
