services:
  - docker

os:
  - Visual Studio 2017

build: off

environment:
  PYTHON: C:\Python36-x64

before_build:
  - echo BEFORE_BUILD
  - echo %APPVEYOR_REPO_BRANCH%
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%path%
  - pip install vcstool
  - pip install EmPy pyparsing pyyaml

build_script:
  - md \dev\ament\src
  - cd \dev\ament
  - curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/%APPVEYOR_REPO_BRANCH%/ament_dotnet_uwp.repos -o ament_dotnet_uwp.repos
  - vcs import src < ament_dotnet_uwp.repos
  - python src\ament\ament_tools\scripts\ament.py build --cmake-args -G "Visual Studio 15 2017 Win64" --
  - call install\local_setup.bat

  - md \dev\ros2\src
  - cd \dev\ros2
  - curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/%APPVEYOR_REPO_BRANCH%/ros2_dotnet_uwp.repos -o ros2_dotnet_uwp.repos
  - vcs import src < ros2_dotnet_uwp.repos
  - cd \dev\ros2\src\ros2\rosidl_typesupport
  - patch -p1 < ..\..\ros2_dotnet/ros2_dotnet/rosidl_typesupport_ros2_uwp.patch
  - cd \dev\ros2
  - ament build --cmake-args -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DTHIRDPARTY=ON -DCOMPILE_EXAMPLES=OFF -DCMAKE_FIND_ROOT_PATH="\dev\ament\install;\dev\ros2\install" -- --skip-packages std_srvs
  - echo BUILD_SCRIPT

after_build:
  - 7z a ros2_uwp.zip \dev\ros2\install
  - appveyor PushArtifact ros2_uwp.zip
