# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install -U setuptools pip
        pip install -U vcstool
        pip install -U colcon-common-extensions
        pip install -U catkin_pkg EmPy lark-parser pyparsing pyyaml numpy
        pip install -U pytest coverage mock
        pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8 pydocstyle
        choco install -y cppcheck
    
    - name: Build ament
      run: |
        set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
        md \dev\ament\src
        cd \dev\ament
        copy $(GITHUB_WORKSPACE)\ros2_dotnet\ament_dotnet_uwp.repos \dev\ament\ament_dotnet_uwp.repos
        vcs import src < ament_dotnet_uwp.repos
        vcs branch
        colcon build --merge-install --cmake-args -A x64
        call install\local_setup.bat  
